### PR TITLE
Add Windows build

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is a required dependency for `librsvg` which in turn is a required dependency for `adwaita-icon-theme` which we want to add to conda-forge.

### CODE REVIEW

**Comment by ryanvolz** [comment]
I'm not sure what's happening with the OSX build, and whether it's a temporary Azure problem or something that actually needs to be fixed due to a change in the build environment since the last build.

**Comment by pkgw** [comment]
I'll try to check out the Mac issue.

FYI, conda-build 3.19.2 is now available and I think I saw some more PR traffic on the prefix detection — maybe the issues are better now?

**Comment by ryanvolz** [comment]
> I'll try to check out the Mac issue.
> 
> FYI, conda-build 3.19.2 is now available and I think I saw some more PR traffic on the prefix detection — maybe the issues are better now?

I had a similar hope, but the build before the temporary pin commit shows that the issue still exists with 3.19.2. It's still something different with Azure as again it works for my local machine.

**Comment by pkgw** [comment]
@ryanvolz Bummer. (BTW, I just noticed your affiliation — I'm a radio astronomer based at the Center for Astrophysics in Cambridge; I've been to Haystack a few times! Funny.)

**Comment by ryanvolz** [comment]
> @ryanvolz Bummer. (BTW, I just noticed your affiliation — I'm a radio astronomer based at the Center for Astrophysics in Cambridge; I've been to Haystack a few times! Funny.)

@pkgw Ha! I've never actually visited the CFA but I am certainly well aware of it from my astronomer co-workers (I'm on the geospace radar side). It's no wonder that we've ended up working on similar segments of the software stack then.

**Review by pkgw — APPROVED** [review]
macOS build succeeded (although the "Upload package" step is taking an inordinate amount of time right now ...)

**Pull request merged**
